# Generated by Django 6.0.7 on 2026-08-07 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API source',
                'verbose_name_plural': 'API sources',
            },
        ),
        migrations.CreateModel(
            name='CatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('raw_payload', models.JSONField()),
                ('reservoir_name', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('fish_type', models.CharField(blank=True, max_length=128)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('bite_status', models.CharField(blank=True, max_length=32)),
                ('time_of_day', models.CharField(blank=True, max_length=64)),
                ('tackle', models.JSONField(blank=True, default=dict)),
                ('bites', models.PositiveIntegerField(default=0)),
                ('caught', models.PositiveIntegerField(default=0)),
                ('quote', models.TextField(blank=True)),
                ('created_at_external', models.DateTimeField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('time_start', models.CharField(blank=True, max_length=16)),
                ('time_end', models.CharField(blank=True, max_length=16)),
                ('fishing_style', models.CharField(blank=True, max_length=128)),
                ('fishing_date', models.DateField(blank=True, null=True)),
                ('photo_tags', models.JSONField(blank=True, default=dict)),
                ('photo_size_tags', models.JSONField(blank=True, default=dict)),
                ('is_spot_member', models.BooleanField(default=False)),
                ('gear_raw', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('first_synced_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches', to='catches.apisource')),
            ],
            options={
                'verbose_name': 'catch record',
                'verbose_name_plural': 'catch records',
                'ordering': ['-created_at_external'],
            },
        ),
        migrations.CreateModel(
            name='CatchTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'catch tag',
                'verbose_name_plural': 'catch tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'reservoir',
                'verbose_name_plural': 'reservoirs',
            },
        ),
        migrations.CreateModel(
            name='SourceUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('initials', models.CharField(blank=True, max_length=16)),
                ('avatar_bg', models.CharField(blank=True, max_length=32)),
                ('raw_payload', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'source user',
                'verbose_name_plural': 'source users',
            },
        ),
        migrations.CreateModel(
            name='CatchLocation',
            fields=[
                ('catch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location', serialize=False, to='catches.catchrecord')),
                ('mode', models.CharField(blank=True, max_length=32)),
                ('display_text', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'catch location',
                'verbose_name_plural': 'catch locations',
            },
        ),
        migrations.CreateModel(
            name='CatchWeather',
            fields=[
                ('catch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='weather', serialize=False, to='catches.catchrecord')),
                ('temp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pressure', models.PositiveIntegerField(blank=True, null=True)),
                ('humidity', models.PositiveIntegerField(blank=True, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('wind_dir', models.CharField(blank=True, max_length=16)),
                ('cloud_cover', models.PositiveIntegerField(blank=True, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('condition', models.CharField(blank=True, max_length=64)),
                ('moon_phase', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('moon_phase_label', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'catch weather',
                'verbose_name_plural': 'catch weather',
            },
        ),
        migrations.CreateModel(
            name='CatchComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at_external', models.DateTimeField(blank=True, null=True)),
                ('catch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catches.catchrecord')),
            ],
            options={
                'verbose_name': 'catch comment',
                'verbose_name_plural': 'catch comments',
                'ordering': ['created_at_external'],
            },
        ),
        migrations.AddField(
            model_name='catchrecord',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='catches', to='catches.catchtag'),
        ),
        migrations.AddField(
            model_name='catchrecord',
            name='reservoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches', to='catches.reservoir'),
        ),
        migrations.AddField(
            model_name='catchrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches', to='catches.sourceuser'),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('records_fetched', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='catches.apisource')),
            ],
            options={
                'verbose_name': 'sync log',
                'verbose_name_plural': 'sync logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CatchPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_path', models.CharField(max_length=512)),
                ('original_url', models.URLField(blank=True, max_length=1024)),
                ('local_file', models.FileField(blank=True, upload_to='catches/%Y/%m/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('download_status', models.CharField(choices=[('pending', 'Pending'), ('downloaded', 'Downloaded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('catch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catches.catchrecord')),
            ],
            options={
                'verbose_name': 'catch photo',
                'verbose_name_plural': 'catch photos',
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('catch', 'original_path'), name='unique_catch_photo_path')],
            },
        ),
        migrations.AddIndex(
            model_name='catchrecord',
            index=models.Index(fields=['fishing_date'], name='catches_cat_fishing_b6b810_idx'),
        ),
        migrations.AddIndex(
            model_name='catchrecord',
            index=models.Index(fields=['fish_type'], name='catches_cat_fish_ty_5ae66c_idx'),
        ),
        migrations.AddIndex(
            model_name='catchrecord',
            index=models.Index(fields=['region'], name='catches_cat_region_22308c_idx'),
        ),
    ]
