# Generated by Django 6.0.7 on 2026-08-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisource',
            name='fetch_url',
            field=models.URLField(blank=True, help_text='URL для загрузки JSON со списком уловов', max_length=1024),
        ),
        migrations.AlterField(
            model_name='apisource',
            name='base_url',
            field=models.URLField(help_text='Базовый URL для скачивания фото', max_length=512),
        ),
    ]
