# Generated by Django 6.0.7 on 2026-08-07 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0002_apisource_fetch_url_alter_apisource_base_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catchrecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catchrecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_catches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catchrecord',
            name='review_status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён')], db_index=True, default='new', max_length=16),
        ),
    ]
