# Generated by Django 6.0.7 on 2026-08-07 09:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0003_catchrecord_confirmed_at_catchrecord_confirmed_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicApiToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название клиента или интеграции",
                        max_length=255,
                    ),
                ),
                (
                    "token",
                    models.CharField(db_index=True, editable=False, max_length=64, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "public API token",
                "verbose_name_plural": "public API tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
